### ISSUE TITLE
Upable to Init

### ISSUE THREAD

**Issue by bendellarocco** [bubenshchykov/hc-cli#4]
I have tried using both api1 and api2 access tokens.  This may be user error.  But I saw the same issue posted before and closed without any code updates

**Comment by bendellarocco** [comment]
I am able to get a json request back using the same token so I am not sure the token is the issue

**Comment by bubenshchykov** [comment]
@bendellarocco hi, honestly i haven't looked at this module for ages.. it's a few lines of code inside, i would just recommend to debug it. i'll accept pull request quickly

**Comment by bendellarocco** [comment]
Solved issue
